name: CancerTrans
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.5
  - biopython=1.78
  - matplotlib=3.1.3
  - numpy=1.18.1
  - pandas=1.0.3
  - pillow=7.0.0
  - prettytable=0.7.2
  - requests=2.23.0
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - rdkit
  - pip
  - pip:
    - pubchempy
